server:
  port: 8081
  context-path: /report

spring:
  application:
    name: tss-report
  # datasource config
  datasource:
    url: jdbc:mysql://dev.tss.com:3306/njit_report?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: njittss
    password: njittss!@#$5678

# MyBatis配置
mybatis:
  mapper-locations: classpath*:com/tss/report/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka-server/eureka/
  instance:
    metadata-map:
      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://dev.tss.com:${server.port}/

logging:
  level:
    root: INFO
    com.tss: DEBUG

management:
  security:
    enabled: false

data:
  serviceId: TSS-DATA
