server:
  port: 8081
#  context-path: /report

spring:
  application:
    name: tss-report
  # 数据源配置
  datasource:
    url: jdbc:mysql://dev.tss.com:3306/njit_report?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

# MyBatis配置
mybatis:
  mapper-locations: classpath*:com/tss/report/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.tss.com:8090/eureka/
  instance:
    metadata-map:
      management:
#        context-path: ${server.context-path}/actuator
#    health-check-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/health
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/swagger-ui.html
#    status-page-url: http://dev.tss.com:${server.port}${server.context-path}/actuator/info
#    home-page-url: http://dev.tss.com:${server.port}/

logging:
  level:
    root: INFO
    com.tss: DEBUG

management:
  security:
    enabled: false

data:
  serviceId: TSS-DATA
